#!/usr/bin/env bash
# Purpose: Create a one-click Linux launcher for the murmurent hi-fi dashboard.
#          Writes a freedesktop .desktop entry into the user's applications
#          menu plus the launcher script it runs. Distro-agnostic: the entry
#          follows the XDG spec, so it shows up in the app menu on Linux Mint
#          (Cinnamon), Ubuntu (GNOME), Fedora (GNOME/KDE), XFCE, MATE, etc.
#          The Linux analogue of scripts/create_mac_app.sh.
# Author:  Mike Hallett
# Date:    2026-07-14
# Usage:   bash scripts/create_linux_launcher.sh
#
# Output:  ~/.local/share/applications/murmurent-dashboard.desktop
#          ~/.local/share/murmurent/murmurent-dashboard-launcher.sh
#          ~/.local/share/icons/murmurent-dashboard.png

set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
APP_NAME="Murmurent Dashboard"
PORT=8770

DATA_DIR="${XDG_DATA_HOME:-$HOME/.local/share}"
APPS_DIR="${DATA_DIR}/applications"
ICONS_DIR="${DATA_DIR}/icons"
LAUNCH_DIR="${DATA_DIR}/murmurent"

LAUNCHER="${LAUNCH_DIR}/murmurent-dashboard-launcher.sh"
DESKTOP="${APPS_DIR}/murmurent-dashboard.desktop"
ICON_SRC="${REPO_DIR}/assets/murmurent_app_icon.png"
ICON_DEST="${ICONS_DIR}/murmurent-dashboard.png"

mkdir -p "$APPS_DIR" "$ICONS_DIR" "$LAUNCH_DIR"

# ── Launcher script ───────────────────────────────────────────────────────────
# Runs with the user's login environment. Finds uv, starts the dashboard
# detached if it isn't already healthy, then opens the browser via xdg-open.

cat > "$LAUNCHER" << LAUNCHER_EOF
#!/usr/bin/env bash
# murmurent Dashboard launcher — generated by scripts/create_linux_launcher.sh
set -euo pipefail

REPO_DIR="${REPO_DIR}"
PORT=${PORT}
URL="http://127.0.0.1:\${PORT}/"
LOG="\$HOME/.murmurent/dashboard.log"
PID_FILE="\$HOME/.murmurent/dashboard.pid"

notify() { command -v notify-send >/dev/null 2>&1 && notify-send "murmurent Dashboard" "\$1" || true; }

# Portable health probe: curl on most desktops, wget as a fallback (minimal
# Fedora/Ubuntu installs). If neither is present, skip polling and open anyway.
healthy() {
  if command -v curl >/dev/null 2>&1; then
    curl -sf "\${URL}healthz" >/dev/null 2>&1
  elif command -v wget >/dev/null 2>&1; then
    wget -q -O /dev/null "\${URL}healthz" >/dev/null 2>&1
  else
    return 2  # no probe tool — caller treats this as "can't tell"
  fi
}

# Find uv — try PATH first then known install locations
UV="\$(command -v uv 2>/dev/null || true)"
if [[ -z "\$UV" ]]; then
  for candidate in "\$HOME/.local/bin/uv" "\$HOME/.cargo/bin/uv" /usr/local/bin/uv /usr/bin/uv; do
    [[ -x "\$candidate" ]] && UV="\$candidate" && break
  done
fi
if [[ -z "\$UV" ]]; then
  notify "Cannot find uv. Install it from https://docs.astral.sh/uv/ then re-run scripts/create_linux_launcher.sh."
  exit 1
fi

# If the server is already healthy, just open the browser
if healthy; then
  xdg-open "\$URL" >/dev/null 2>&1 || true
  exit 0
fi

# Start the server detached
MURMURENT_USER="\$(head -1 "\$HOME/.murmurent/user" 2>/dev/null | tr -d '[:space:]')"
export MURMURENT_USER
mkdir -p "\$HOME/.murmurent"
cd "\$REPO_DIR"
nohup "\$UV" run murmurent dashboard --hifi --port "\$PORT" > "\$LOG" 2>&1 &
echo \$! > "\$PID_FILE"

# No probe tool (no curl/wget): give the server a moment, then open the browser.
if ! command -v curl >/dev/null 2>&1 && ! command -v wget >/dev/null 2>&1; then
  sleep 3
  xdg-open "\$URL" >/dev/null 2>&1 || true
  exit 0
fi

# Poll until the server is ready (max ~9 s)
for i in \$(seq 1 30); do
  sleep 0.3
  if healthy; then
    xdg-open "\$URL" >/dev/null 2>&1 || true
    notify "Dashboard is ready"
    exit 0
  fi
done

notify "Server did not start in time. Check ~/.murmurent/dashboard.log for details."
exit 1
LAUNCHER_EOF

chmod +x "$LAUNCHER"

# ── Icon ──────────────────────────────────────────────────────────────────────

if [[ -f "$ICON_SRC" ]]; then
  cp "$ICON_SRC" "$ICON_DEST"
  echo "  Icon installed: $ICON_DEST"
else
  ICON_DEST="utilities-terminal"  # fall back to a stock theme icon name
  echo "  Icon source not found at $ICON_SRC — using a stock icon."
fi

# ── Desktop entry ─────────────────────────────────────────────────────────────

cat > "$DESKTOP" << DESKTOP_EOF
[Desktop Entry]
Type=Application
Version=1.0
Name=${APP_NAME}
GenericName=Research dashboard
Comment=Open the murmurent dashboard in your browser
Exec=${LAUNCHER}
Icon=${ICON_DEST}
Terminal=false
Categories=Development;
Keywords=murmurent;dashboard;research;
StartupNotify=true
DESKTOP_EOF

chmod +x "$DESKTOP"

# Refresh the menu database so the entry appears without a re-login (best-effort)
if command -v update-desktop-database >/dev/null 2>&1; then
  update-desktop-database "$APPS_DIR" >/dev/null 2>&1 || true
fi

# ── Done ──────────────────────────────────────────────────────────────────────

echo ""
echo "✓ Created: ${DESKTOP}"
echo ""
echo "  \"${APP_NAME}\" should now appear in your applications menu."
echo "  (Search for \"murmurent\" — you can right-click → Add to Desktop/Panel.)"
echo ""
echo "  Logs: ~/.murmurent/dashboard.log"
