#!/usr/bin/env bash
# Purpose: Create "Murmurent Dashboard.app" — a one-click macOS launcher for the
#          wigamig hi-fi dashboard.  Run once after cloning or reinstalling.
# Author:  Mike Hallett
# Date:    2026-05-11
# Usage:   bash scripts/create_mac_app.sh [--dest /path/to/output/dir]
#
# Output:  ~/Applications/Murmurent Dashboard.app  (or --dest if given)

set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
APP_NAME="Murmurent Dashboard"
DEST_DIR="${HOME}/Applications"
ICON_SRC="${REPO_DIR}/assets/mustang_logo.jpg"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dest) DEST_DIR="$2"; shift 2 ;;
    *) echo "Unknown argument: $1" >&2; exit 1 ;;
  esac
done

APP_PATH="${DEST_DIR}/${APP_NAME}.app"

# ── Create bundle skeleton ────────────────────────────────────────────────────

rm -rf "$APP_PATH"
mkdir -p "${APP_PATH}/Contents/MacOS"
mkdir -p "${APP_PATH}/Contents/Resources"

# ── Main executable shell script ──────────────────────────────────────────────
#
# Using a shell script (not an AppleScript applet) as the main executable
# avoids AppleScript permission prompts on macOS Ventura/Sequoia.
# The script runs with the user's full zsh login environment.

LAUNCHER="${APP_PATH}/Contents/MacOS/wigamig-launcher"

cat > "$LAUNCHER" << LAUNCHER_EOF
#!/bin/zsh -l
# wigamig Dashboard launcher — generated by scripts/create_mac_app.sh

REPO_DIR="${REPO_DIR}"
PORT=8770
URL="http://127.0.0.1:\${PORT}/"
LOG="\$HOME/.wigamig/dashboard.log"
PID_FILE="\$HOME/.wigamig/dashboard.pid"

# Find uv — try PATH first then known install locations
UV="\$(command -v uv 2>/dev/null)"
if [[ -z "\$UV" ]]; then
  for candidate in "\$HOME/.local/bin/uv" "\$HOME/.cargo/bin/uv" /opt/homebrew/bin/uv /usr/local/bin/uv; do
    [[ -x "\$candidate" ]] && UV="\$candidate" && break
  done
fi

if [[ -z "\$UV" ]]; then
  osascript -e 'display alert "wigamig Dashboard" message "Cannot find uv. Install it from https://docs.astral.sh/uv/ then run scripts/create_mac_app.sh again." as critical' 2>/dev/null
  exit 1
fi

# If server is already healthy, just open the browser
if curl -sf "\${URL}healthz" >/dev/null 2>&1; then
  open "\$URL"
  exit 0
fi

# Start the server detached
WIGAMIG_USER="\$(head -1 "\$HOME/.wigamig/user" 2>/dev/null | tr -d '[:space:]')"
export WIGAMIG_USER
mkdir -p "\$HOME/.wigamig"
cd "\$REPO_DIR"
nohup "\$UV" run murmurent dashboard --hifi --port "\$PORT" > "\$LOG" 2>&1 &
echo \$! > "\$PID_FILE"

# Poll until the server is ready (max ~9 s)
for i in \$(seq 1 30); do
  sleep 0.3
  if curl -sf "\${URL}healthz" >/dev/null 2>&1; then
    open "\$URL"
    osascript -e 'display notification "Dashboard is ready" with title "wigamig Dashboard"' 2>/dev/null || true
    exit 0
  fi
done

osascript -e 'display alert "wigamig Dashboard" message "Server did not start in time.\nCheck ~/.wigamig/dashboard.log for details." as critical' 2>/dev/null
exit 1
LAUNCHER_EOF

chmod +x "$LAUNCHER"

# ── Info.plist ────────────────────────────────────────────────────────────────

cat > "${APP_PATH}/Contents/Info.plist" << 'PLIST_EOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key>
    <string>wigamig-launcher</string>
    <key>CFBundleIconFile</key>
    <string>wigamig</string>
    <key>CFBundleIdentifier</key>
    <string>ca.uwo.hallett.wigamig-dashboard</string>
    <key>CFBundleName</key>
    <string>Murmurent Dashboard</string>
    <key>CFBundleDisplayName</key>
    <string>Murmurent Dashboard</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleVersion</key>
    <string>1.0</string>
    <key>CFBundleShortVersionString</key>
    <string>1.0</string>
    <key>LSMinimumSystemVersion</key>
    <string>12.0</string>
    <key>NSHighResolutionCapable</key>
    <true/>
    <key>NSAppleEventsUsageDescription</key>
    <string>wigamig Dashboard uses notifications to tell you when the server is ready.</string>
</dict>
</plist>
PLIST_EOF

# Required PkgInfo for macOS to recognise this as an app
printf 'APPL????' > "${APP_PATH}/Contents/PkgInfo"

# ── Generate and apply icon ───────────────────────────────────────────────────

apply_icon() {
    local png="$1"
    local app="$2"
    local iconset
    iconset="$(mktemp -d /tmp/wigamig_iconset_XXXXXX)"
    # Apple iconset valid logical sizes: 16 32 128 256 512 (no 64).
    # For each logical size sz, base file = sz×sz, @2x file = 2sz×2sz.
    local sizes=(16 32 128 256 512)
    for sz in "${sizes[@]}"; do
        sips -z "$sz" "$sz" -s format png "$png" --out "${iconset}/icon_${sz}x${sz}.png"         >/dev/null 2>&1
        sips -z "$((sz*2))" "$((sz*2))" -s format png "$png" --out "${iconset}/icon_${sz}x${sz}@2x.png" >/dev/null 2>&1
    done
    # iconutil requires the directory to be named *.iconset
    mv "$iconset" "${iconset}.iconset"
    iconutil -c icns "${iconset}.iconset" -o "${app}/Contents/Resources/murmurent.icns" 2>/dev/null
    rm -rf "${iconset}.iconset"
}

if [[ -f "$ICON_SRC" ]]; then
    apply_icon "$ICON_SRC" "$APP_PATH" 2>/dev/null && \
        echo "  Icon applied (mustang_logo.jpg)." || echo "  Icon conversion skipped (sips/iconutil issue)."
else
    echo "  Icon source not found at $ICON_SRC — app will use default icon."
fi

# Clear any quarantine flags that may have been inherited
xattr -cr "$APP_PATH" 2>/dev/null || true

# ── Done ──────────────────────────────────────────────────────────────────────

echo ""
echo "✓ Created: ${APP_PATH}"
echo ""
echo "  To launch with one click:"
echo "    1. Open Finder → go to ~/Applications"
echo "    2. Drag \"${APP_NAME}\" to your Dock"
echo "    3. Click the Dock icon — your dashboard opens in the browser"
echo ""
echo "  Logs: ~/.wigamig/dashboard.log"
